/*
airEml - API

airEml - API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package AirEml

import (
	"encoding/json"
	"fmt"
)

// checks if the PushTemplateContentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PushTemplateContentRequest{}

// PushTemplateContentRequest struct for PushTemplateContentRequest
type PushTemplateContentRequest struct {
	// The is a title of the push notification.
	Title string `json:"title"`
	// The is a body of the push notification.
	Body string `json:"body"`
	// The notification's icon. Sets the notification icon to myicon for drawable resource myicon. If you don't send this key in the request, FCM displays the launcher icon specified in your app manifest.
	Icon NullableString `json:"icon,omitempty"`
	// Contains the URL of an image that is going to be downloaded on the device and displayed in a notification. JPEG, PNG, BMP have full support across platforms. Animated GIF and video only work on iOS. WebP and HEIF have varying levels of support across platforms and platform versions. Android has 1MB image size limit. 
	Image NullableString `json:"image,omitempty"`
	// The link to open when the user clicks on the notification. For all URL values, HTTPS is required.
	Link NullableString `json:"link,omitempty"`
	// The additional data used for send push notification if user wants to add some custom data in request
	Data *map[string]string `json:"data,omitempty"`
}

type _PushTemplateContentRequest PushTemplateContentRequest

// NewPushTemplateContentRequest instantiates a new PushTemplateContentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPushTemplateContentRequest(title string, body string) *PushTemplateContentRequest {
	this := PushTemplateContentRequest{}
	this.Title = title
	this.Body = body
	return &this
}

// NewPushTemplateContentRequestWithDefaults instantiates a new PushTemplateContentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPushTemplateContentRequestWithDefaults() *PushTemplateContentRequest {
	this := PushTemplateContentRequest{}
	return &this
}

// GetTitle returns the Title field value
func (o *PushTemplateContentRequest) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *PushTemplateContentRequest) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *PushTemplateContentRequest) SetTitle(v string) {
	o.Title = v
}

// GetBody returns the Body field value
func (o *PushTemplateContentRequest) GetBody() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Body
}

// GetBodyOk returns a tuple with the Body field value
// and a boolean to check if the value has been set.
func (o *PushTemplateContentRequest) GetBodyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Body, true
}

// SetBody sets field value
func (o *PushTemplateContentRequest) SetBody(v string) {
	o.Body = v
}

// GetIcon returns the Icon field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PushTemplateContentRequest) GetIcon() string {
	if o == nil || IsNil(o.Icon.Get()) {
		var ret string
		return ret
	}
	return *o.Icon.Get()
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PushTemplateContentRequest) GetIconOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Icon.Get(), o.Icon.IsSet()
}

// HasIcon returns a boolean if a field has been set.
func (o *PushTemplateContentRequest) HasIcon() bool {
	if o != nil && o.Icon.IsSet() {
		return true
	}

	return false
}

// SetIcon gets a reference to the given NullableString and assigns it to the Icon field.
func (o *PushTemplateContentRequest) SetIcon(v string) {
	o.Icon.Set(&v)
}
// SetIconNil sets the value for Icon to be an explicit nil
func (o *PushTemplateContentRequest) SetIconNil() {
	o.Icon.Set(nil)
}

// UnsetIcon ensures that no value is present for Icon, not even an explicit nil
func (o *PushTemplateContentRequest) UnsetIcon() {
	o.Icon.Unset()
}

// GetImage returns the Image field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PushTemplateContentRequest) GetImage() string {
	if o == nil || IsNil(o.Image.Get()) {
		var ret string
		return ret
	}
	return *o.Image.Get()
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PushTemplateContentRequest) GetImageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Image.Get(), o.Image.IsSet()
}

// HasImage returns a boolean if a field has been set.
func (o *PushTemplateContentRequest) HasImage() bool {
	if o != nil && o.Image.IsSet() {
		return true
	}

	return false
}

// SetImage gets a reference to the given NullableString and assigns it to the Image field.
func (o *PushTemplateContentRequest) SetImage(v string) {
	o.Image.Set(&v)
}
// SetImageNil sets the value for Image to be an explicit nil
func (o *PushTemplateContentRequest) SetImageNil() {
	o.Image.Set(nil)
}

// UnsetImage ensures that no value is present for Image, not even an explicit nil
func (o *PushTemplateContentRequest) UnsetImage() {
	o.Image.Unset()
}

// GetLink returns the Link field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PushTemplateContentRequest) GetLink() string {
	if o == nil || IsNil(o.Link.Get()) {
		var ret string
		return ret
	}
	return *o.Link.Get()
}

// GetLinkOk returns a tuple with the Link field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PushTemplateContentRequest) GetLinkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Link.Get(), o.Link.IsSet()
}

// HasLink returns a boolean if a field has been set.
func (o *PushTemplateContentRequest) HasLink() bool {
	if o != nil && o.Link.IsSet() {
		return true
	}

	return false
}

// SetLink gets a reference to the given NullableString and assigns it to the Link field.
func (o *PushTemplateContentRequest) SetLink(v string) {
	o.Link.Set(&v)
}
// SetLinkNil sets the value for Link to be an explicit nil
func (o *PushTemplateContentRequest) SetLinkNil() {
	o.Link.Set(nil)
}

// UnsetLink ensures that no value is present for Link, not even an explicit nil
func (o *PushTemplateContentRequest) UnsetLink() {
	o.Link.Unset()
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *PushTemplateContentRequest) GetData() map[string]string {
	if o == nil || IsNil(o.Data) {
		var ret map[string]string
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PushTemplateContentRequest) GetDataOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *PushTemplateContentRequest) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]string and assigns it to the Data field.
func (o *PushTemplateContentRequest) SetData(v map[string]string) {
	o.Data = &v
}

func (o PushTemplateContentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PushTemplateContentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["title"] = o.Title
	toSerialize["body"] = o.Body
	if o.Icon.IsSet() {
		toSerialize["icon"] = o.Icon.Get()
	}
	if o.Image.IsSet() {
		toSerialize["image"] = o.Image.Get()
	}
	if o.Link.IsSet() {
		toSerialize["link"] = o.Link.Get()
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

func (o *PushTemplateContentRequest) UnmarshalJSON(bytes []byte) (err error) {
    // This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"title",
		"body",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPushTemplateContentRequest := _PushTemplateContentRequest{}

	err = json.Unmarshal(bytes, &varPushTemplateContentRequest)

	if err != nil {
		return err
	}

	*o = PushTemplateContentRequest(varPushTemplateContentRequest)

	return err
}

type NullablePushTemplateContentRequest struct {
	value *PushTemplateContentRequest
	isSet bool
}

func (v NullablePushTemplateContentRequest) Get() *PushTemplateContentRequest {
	return v.value
}

func (v *NullablePushTemplateContentRequest) Set(val *PushTemplateContentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePushTemplateContentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePushTemplateContentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePushTemplateContentRequest(val *PushTemplateContentRequest) *NullablePushTemplateContentRequest {
	return &NullablePushTemplateContentRequest{value: val, isSet: true}
}

func (v NullablePushTemplateContentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePushTemplateContentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


