/*
airEml - API

airEml - API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package AirEml

import (
	"encoding/json"
	"time"
)

// checks if the EmailChannelRoutingRules type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailChannelRoutingRules{}

// EmailChannelRoutingRules struct for EmailChannelRoutingRules
type EmailChannelRoutingRules struct {
	// The ID of the Routing-rule
	Id *string `json:"id,omitempty"`
	// The ID of the Transport
	TransportId *string `json:"transport_id,omitempty"`
	// The ID of the Sender
	SenderId *string `json:"sender_id,omitempty"`
	// Whether the Routing-rule is reserved or not
	IsReserved *bool `json:"is_reserved,omitempty"`
	// The status of the Routing-rule. Every digit matters: 1 - active, 2 - inactive.
	Status *int32 `json:"status,omitempty"`
	// The datetime when the Template Content was created.
	CreatedAt *time.Time `json:"created_at,omitempty"`
}

// NewEmailChannelRoutingRules instantiates a new EmailChannelRoutingRules object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailChannelRoutingRules() *EmailChannelRoutingRules {
	this := EmailChannelRoutingRules{}
	return &this
}

// NewEmailChannelRoutingRulesWithDefaults instantiates a new EmailChannelRoutingRules object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailChannelRoutingRulesWithDefaults() *EmailChannelRoutingRules {
	this := EmailChannelRoutingRules{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *EmailChannelRoutingRules) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailChannelRoutingRules) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *EmailChannelRoutingRules) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *EmailChannelRoutingRules) SetId(v string) {
	o.Id = &v
}

// GetTransportId returns the TransportId field value if set, zero value otherwise.
func (o *EmailChannelRoutingRules) GetTransportId() string {
	if o == nil || IsNil(o.TransportId) {
		var ret string
		return ret
	}
	return *o.TransportId
}

// GetTransportIdOk returns a tuple with the TransportId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailChannelRoutingRules) GetTransportIdOk() (*string, bool) {
	if o == nil || IsNil(o.TransportId) {
		return nil, false
	}
	return o.TransportId, true
}

// HasTransportId returns a boolean if a field has been set.
func (o *EmailChannelRoutingRules) HasTransportId() bool {
	if o != nil && !IsNil(o.TransportId) {
		return true
	}

	return false
}

// SetTransportId gets a reference to the given string and assigns it to the TransportId field.
func (o *EmailChannelRoutingRules) SetTransportId(v string) {
	o.TransportId = &v
}

// GetSenderId returns the SenderId field value if set, zero value otherwise.
func (o *EmailChannelRoutingRules) GetSenderId() string {
	if o == nil || IsNil(o.SenderId) {
		var ret string
		return ret
	}
	return *o.SenderId
}

// GetSenderIdOk returns a tuple with the SenderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailChannelRoutingRules) GetSenderIdOk() (*string, bool) {
	if o == nil || IsNil(o.SenderId) {
		return nil, false
	}
	return o.SenderId, true
}

// HasSenderId returns a boolean if a field has been set.
func (o *EmailChannelRoutingRules) HasSenderId() bool {
	if o != nil && !IsNil(o.SenderId) {
		return true
	}

	return false
}

// SetSenderId gets a reference to the given string and assigns it to the SenderId field.
func (o *EmailChannelRoutingRules) SetSenderId(v string) {
	o.SenderId = &v
}

// GetIsReserved returns the IsReserved field value if set, zero value otherwise.
func (o *EmailChannelRoutingRules) GetIsReserved() bool {
	if o == nil || IsNil(o.IsReserved) {
		var ret bool
		return ret
	}
	return *o.IsReserved
}

// GetIsReservedOk returns a tuple with the IsReserved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailChannelRoutingRules) GetIsReservedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsReserved) {
		return nil, false
	}
	return o.IsReserved, true
}

// HasIsReserved returns a boolean if a field has been set.
func (o *EmailChannelRoutingRules) HasIsReserved() bool {
	if o != nil && !IsNil(o.IsReserved) {
		return true
	}

	return false
}

// SetIsReserved gets a reference to the given bool and assigns it to the IsReserved field.
func (o *EmailChannelRoutingRules) SetIsReserved(v bool) {
	o.IsReserved = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *EmailChannelRoutingRules) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailChannelRoutingRules) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *EmailChannelRoutingRules) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *EmailChannelRoutingRules) SetStatus(v int32) {
	o.Status = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *EmailChannelRoutingRules) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailChannelRoutingRules) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *EmailChannelRoutingRules) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *EmailChannelRoutingRules) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

func (o EmailChannelRoutingRules) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailChannelRoutingRules) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.TransportId) {
		toSerialize["transport_id"] = o.TransportId
	}
	if !IsNil(o.SenderId) {
		toSerialize["sender_id"] = o.SenderId
	}
	if !IsNil(o.IsReserved) {
		toSerialize["is_reserved"] = o.IsReserved
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableEmailChannelRoutingRules struct {
	value *EmailChannelRoutingRules
	isSet bool
}

func (v NullableEmailChannelRoutingRules) Get() *EmailChannelRoutingRules {
	return v.value
}

func (v *NullableEmailChannelRoutingRules) Set(val *EmailChannelRoutingRules) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailChannelRoutingRules) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailChannelRoutingRules) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailChannelRoutingRules(val *EmailChannelRoutingRules) *NullableEmailChannelRoutingRules {
	return &NullableEmailChannelRoutingRules{value: val, isSet: true}
}

func (v NullableEmailChannelRoutingRules) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailChannelRoutingRules) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


