/*
airEml - API

airEml - API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package AirEml

import (
	"encoding/json"
)

// checks if the SmsRoutingRuleResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SmsRoutingRuleResponse{}

// SmsRoutingRuleResponse struct for SmsRoutingRuleResponse
type SmsRoutingRuleResponse struct {
	Data *SmsRoutingRule `json:"data,omitempty"`
}

// NewSmsRoutingRuleResponse instantiates a new SmsRoutingRuleResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSmsRoutingRuleResponse() *SmsRoutingRuleResponse {
	this := SmsRoutingRuleResponse{}
	return &this
}

// NewSmsRoutingRuleResponseWithDefaults instantiates a new SmsRoutingRuleResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSmsRoutingRuleResponseWithDefaults() *SmsRoutingRuleResponse {
	this := SmsRoutingRuleResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *SmsRoutingRuleResponse) GetData() SmsRoutingRule {
	if o == nil || IsNil(o.Data) {
		var ret SmsRoutingRule
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmsRoutingRuleResponse) GetDataOk() (*SmsRoutingRule, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *SmsRoutingRuleResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given SmsRoutingRule and assigns it to the Data field.
func (o *SmsRoutingRuleResponse) SetData(v SmsRoutingRule) {
	o.Data = &v
}

func (o SmsRoutingRuleResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SmsRoutingRuleResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableSmsRoutingRuleResponse struct {
	value *SmsRoutingRuleResponse
	isSet bool
}

func (v NullableSmsRoutingRuleResponse) Get() *SmsRoutingRuleResponse {
	return v.value
}

func (v *NullableSmsRoutingRuleResponse) Set(val *SmsRoutingRuleResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSmsRoutingRuleResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSmsRoutingRuleResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSmsRoutingRuleResponse(val *SmsRoutingRuleResponse) *NullableSmsRoutingRuleResponse {
	return &NullableSmsRoutingRuleResponse{value: val, isSet: true}
}

func (v NullableSmsRoutingRuleResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSmsRoutingRuleResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


