/*
airEml - API

airEml - API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package AirEml

import (
	"encoding/json"
)

// checks if the TransportWebhookGenerateResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransportWebhookGenerateResponseData{}

// TransportWebhookGenerateResponseData struct for TransportWebhookGenerateResponseData
type TransportWebhookGenerateResponseData struct {
	// Webhook link.
	WebhookUrl *string `json:"webhook_url,omitempty"`
}

// NewTransportWebhookGenerateResponseData instantiates a new TransportWebhookGenerateResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransportWebhookGenerateResponseData() *TransportWebhookGenerateResponseData {
	this := TransportWebhookGenerateResponseData{}
	return &this
}

// NewTransportWebhookGenerateResponseDataWithDefaults instantiates a new TransportWebhookGenerateResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransportWebhookGenerateResponseDataWithDefaults() *TransportWebhookGenerateResponseData {
	this := TransportWebhookGenerateResponseData{}
	return &this
}

// GetWebhookUrl returns the WebhookUrl field value if set, zero value otherwise.
func (o *TransportWebhookGenerateResponseData) GetWebhookUrl() string {
	if o == nil || IsNil(o.WebhookUrl) {
		var ret string
		return ret
	}
	return *o.WebhookUrl
}

// GetWebhookUrlOk returns a tuple with the WebhookUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportWebhookGenerateResponseData) GetWebhookUrlOk() (*string, bool) {
	if o == nil || IsNil(o.WebhookUrl) {
		return nil, false
	}
	return o.WebhookUrl, true
}

// HasWebhookUrl returns a boolean if a field has been set.
func (o *TransportWebhookGenerateResponseData) HasWebhookUrl() bool {
	if o != nil && !IsNil(o.WebhookUrl) {
		return true
	}

	return false
}

// SetWebhookUrl gets a reference to the given string and assigns it to the WebhookUrl field.
func (o *TransportWebhookGenerateResponseData) SetWebhookUrl(v string) {
	o.WebhookUrl = &v
}

func (o TransportWebhookGenerateResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransportWebhookGenerateResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.WebhookUrl) {
		toSerialize["webhook_url"] = o.WebhookUrl
	}
	return toSerialize, nil
}

type NullableTransportWebhookGenerateResponseData struct {
	value *TransportWebhookGenerateResponseData
	isSet bool
}

func (v NullableTransportWebhookGenerateResponseData) Get() *TransportWebhookGenerateResponseData {
	return v.value
}

func (v *NullableTransportWebhookGenerateResponseData) Set(val *TransportWebhookGenerateResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableTransportWebhookGenerateResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableTransportWebhookGenerateResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransportWebhookGenerateResponseData(val *TransportWebhookGenerateResponseData) *NullableTransportWebhookGenerateResponseData {
	return &NullableTransportWebhookGenerateResponseData{value: val, isSet: true}
}

func (v NullableTransportWebhookGenerateResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransportWebhookGenerateResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


