/*
airEml - API

airEml - API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package AirEml

import (
	"encoding/json"
)

// checks if the AudienceFilterCollectionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AudienceFilterCollectionResponse{}

// AudienceFilterCollectionResponse struct for AudienceFilterCollectionResponse
type AudienceFilterCollectionResponse struct {
	Links *CollectionLinks `json:"links,omitempty"`
	Meta *CollectionMeta `json:"meta,omitempty"`
	Data []AudienceFilter `json:"data,omitempty"`
}

// NewAudienceFilterCollectionResponse instantiates a new AudienceFilterCollectionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAudienceFilterCollectionResponse() *AudienceFilterCollectionResponse {
	this := AudienceFilterCollectionResponse{}
	return &this
}

// NewAudienceFilterCollectionResponseWithDefaults instantiates a new AudienceFilterCollectionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAudienceFilterCollectionResponseWithDefaults() *AudienceFilterCollectionResponse {
	this := AudienceFilterCollectionResponse{}
	return &this
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *AudienceFilterCollectionResponse) GetLinks() CollectionLinks {
	if o == nil || IsNil(o.Links) {
		var ret CollectionLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AudienceFilterCollectionResponse) GetLinksOk() (*CollectionLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *AudienceFilterCollectionResponse) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given CollectionLinks and assigns it to the Links field.
func (o *AudienceFilterCollectionResponse) SetLinks(v CollectionLinks) {
	o.Links = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *AudienceFilterCollectionResponse) GetMeta() CollectionMeta {
	if o == nil || IsNil(o.Meta) {
		var ret CollectionMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AudienceFilterCollectionResponse) GetMetaOk() (*CollectionMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *AudienceFilterCollectionResponse) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given CollectionMeta and assigns it to the Meta field.
func (o *AudienceFilterCollectionResponse) SetMeta(v CollectionMeta) {
	o.Meta = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *AudienceFilterCollectionResponse) GetData() []AudienceFilter {
	if o == nil || IsNil(o.Data) {
		var ret []AudienceFilter
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AudienceFilterCollectionResponse) GetDataOk() ([]AudienceFilter, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AudienceFilterCollectionResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []AudienceFilter and assigns it to the Data field.
func (o *AudienceFilterCollectionResponse) SetData(v []AudienceFilter) {
	o.Data = v
}

func (o AudienceFilterCollectionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AudienceFilterCollectionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableAudienceFilterCollectionResponse struct {
	value *AudienceFilterCollectionResponse
	isSet bool
}

func (v NullableAudienceFilterCollectionResponse) Get() *AudienceFilterCollectionResponse {
	return v.value
}

func (v *NullableAudienceFilterCollectionResponse) Set(val *AudienceFilterCollectionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAudienceFilterCollectionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAudienceFilterCollectionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAudienceFilterCollectionResponse(val *AudienceFilterCollectionResponse) *NullableAudienceFilterCollectionResponse {
	return &NullableAudienceFilterCollectionResponse{value: val, isSet: true}
}

func (v NullableAudienceFilterCollectionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAudienceFilterCollectionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


