/*
airEml - API

airEml - API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package AirEml

import (
	"encoding/json"
)

// checks if the EmailTemplateContentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailTemplateContentResponse{}

// EmailTemplateContentResponse struct for EmailTemplateContentResponse
type EmailTemplateContentResponse struct {
	Data *EmailTemplateContent `json:"data,omitempty"`
}

// NewEmailTemplateContentResponse instantiates a new EmailTemplateContentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailTemplateContentResponse() *EmailTemplateContentResponse {
	this := EmailTemplateContentResponse{}
	return &this
}

// NewEmailTemplateContentResponseWithDefaults instantiates a new EmailTemplateContentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailTemplateContentResponseWithDefaults() *EmailTemplateContentResponse {
	this := EmailTemplateContentResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *EmailTemplateContentResponse) GetData() EmailTemplateContent {
	if o == nil || IsNil(o.Data) {
		var ret EmailTemplateContent
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailTemplateContentResponse) GetDataOk() (*EmailTemplateContent, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *EmailTemplateContentResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given EmailTemplateContent and assigns it to the Data field.
func (o *EmailTemplateContentResponse) SetData(v EmailTemplateContent) {
	o.Data = &v
}

func (o EmailTemplateContentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailTemplateContentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableEmailTemplateContentResponse struct {
	value *EmailTemplateContentResponse
	isSet bool
}

func (v NullableEmailTemplateContentResponse) Get() *EmailTemplateContentResponse {
	return v.value
}

func (v *NullableEmailTemplateContentResponse) Set(val *EmailTemplateContentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailTemplateContentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailTemplateContentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailTemplateContentResponse(val *EmailTemplateContentResponse) *NullableEmailTemplateContentResponse {
	return &NullableEmailTemplateContentResponse{value: val, isSet: true}
}

func (v NullableEmailTemplateContentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailTemplateContentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


