/*
airEml - API

airEml - API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package AirEml

import (
	"encoding/json"
	"time"
)

// checks if the AudienceFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AudienceFilter{}

// AudienceFilter struct for AudienceFilter
type AudienceFilter struct {
	// The unique identifier of the Segment.
	Id *string `json:"id,omitempty"`
	// The rules of the Filter.
	Rules []AudienceRule `json:"rules,omitempty"`
	// The datetime when the Platform was created.
	CreatedAt *time.Time `json:"created_at,omitempty"`
}

// NewAudienceFilter instantiates a new AudienceFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAudienceFilter() *AudienceFilter {
	this := AudienceFilter{}
	return &this
}

// NewAudienceFilterWithDefaults instantiates a new AudienceFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAudienceFilterWithDefaults() *AudienceFilter {
	this := AudienceFilter{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AudienceFilter) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AudienceFilter) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AudienceFilter) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AudienceFilter) SetId(v string) {
	o.Id = &v
}

// GetRules returns the Rules field value if set, zero value otherwise.
func (o *AudienceFilter) GetRules() []AudienceRule {
	if o == nil || IsNil(o.Rules) {
		var ret []AudienceRule
		return ret
	}
	return o.Rules
}

// GetRulesOk returns a tuple with the Rules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AudienceFilter) GetRulesOk() ([]AudienceRule, bool) {
	if o == nil || IsNil(o.Rules) {
		return nil, false
	}
	return o.Rules, true
}

// HasRules returns a boolean if a field has been set.
func (o *AudienceFilter) HasRules() bool {
	if o != nil && !IsNil(o.Rules) {
		return true
	}

	return false
}

// SetRules gets a reference to the given []AudienceRule and assigns it to the Rules field.
func (o *AudienceFilter) SetRules(v []AudienceRule) {
	o.Rules = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *AudienceFilter) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AudienceFilter) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *AudienceFilter) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *AudienceFilter) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

func (o AudienceFilter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AudienceFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Rules) {
		toSerialize["rules"] = o.Rules
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableAudienceFilter struct {
	value *AudienceFilter
	isSet bool
}

func (v NullableAudienceFilter) Get() *AudienceFilter {
	return v.value
}

func (v *NullableAudienceFilter) Set(val *AudienceFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableAudienceFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableAudienceFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAudienceFilter(val *AudienceFilter) *NullableAudienceFilter {
	return &NullableAudienceFilter{value: val, isSet: true}
}

func (v NullableAudienceFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAudienceFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


