/*
airEml - API

airEml - API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package AirEml

import (
	"encoding/json"
	"time"
)

// checks if the AudienceRecipientTag type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AudienceRecipientTag{}

// AudienceRecipientTag struct for AudienceRecipientTag
type AudienceRecipientTag struct {
	// The unique identifier of the Tag.
	Id *string `json:"id,omitempty"`
	// The name of the Tag.
	Name *string `json:"name,omitempty"`
	// The datetime when the Recipient was added to the Tag.
	CreatedAt *time.Time `json:"created_at,omitempty"`
}

// NewAudienceRecipientTag instantiates a new AudienceRecipientTag object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAudienceRecipientTag() *AudienceRecipientTag {
	this := AudienceRecipientTag{}
	return &this
}

// NewAudienceRecipientTagWithDefaults instantiates a new AudienceRecipientTag object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAudienceRecipientTagWithDefaults() *AudienceRecipientTag {
	this := AudienceRecipientTag{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AudienceRecipientTag) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AudienceRecipientTag) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AudienceRecipientTag) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AudienceRecipientTag) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AudienceRecipientTag) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AudienceRecipientTag) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AudienceRecipientTag) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AudienceRecipientTag) SetName(v string) {
	o.Name = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *AudienceRecipientTag) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AudienceRecipientTag) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *AudienceRecipientTag) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *AudienceRecipientTag) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

func (o AudienceRecipientTag) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AudienceRecipientTag) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableAudienceRecipientTag struct {
	value *AudienceRecipientTag
	isSet bool
}

func (v NullableAudienceRecipientTag) Get() *AudienceRecipientTag {
	return v.value
}

func (v *NullableAudienceRecipientTag) Set(val *AudienceRecipientTag) {
	v.value = val
	v.isSet = true
}

func (v NullableAudienceRecipientTag) IsSet() bool {
	return v.isSet
}

func (v *NullableAudienceRecipientTag) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAudienceRecipientTag(val *AudienceRecipientTag) *NullableAudienceRecipientTag {
	return &NullableAudienceRecipientTag{value: val, isSet: true}
}

func (v NullableAudienceRecipientTag) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAudienceRecipientTag) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


