/*
airEml - API

airEml - API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package AirEml

import (
	"encoding/json"
)

// checks if the AudienceSegmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AudienceSegmentRequest{}

// AudienceSegmentRequest struct for AudienceSegmentRequest
type AudienceSegmentRequest struct {
	// The name of the Segment.
	Name *string `json:"name,omitempty"`
}

// NewAudienceSegmentRequest instantiates a new AudienceSegmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAudienceSegmentRequest() *AudienceSegmentRequest {
	this := AudienceSegmentRequest{}
	return &this
}

// NewAudienceSegmentRequestWithDefaults instantiates a new AudienceSegmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAudienceSegmentRequestWithDefaults() *AudienceSegmentRequest {
	this := AudienceSegmentRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AudienceSegmentRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AudienceSegmentRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AudienceSegmentRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AudienceSegmentRequest) SetName(v string) {
	o.Name = &v
}

func (o AudienceSegmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AudienceSegmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableAudienceSegmentRequest struct {
	value *AudienceSegmentRequest
	isSet bool
}

func (v NullableAudienceSegmentRequest) Get() *AudienceSegmentRequest {
	return v.value
}

func (v *NullableAudienceSegmentRequest) Set(val *AudienceSegmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAudienceSegmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAudienceSegmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAudienceSegmentRequest(val *AudienceSegmentRequest) *NullableAudienceSegmentRequest {
	return &NullableAudienceSegmentRequest{value: val, isSet: true}
}

func (v NullableAudienceSegmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAudienceSegmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


