/*
airEml - API

airEml - API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package AirEml

import (
	"encoding/json"
	"time"
)

// checks if the EmailNotification type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailNotification{}

// EmailNotification struct for EmailNotification
type EmailNotification struct {
	// The unique identifier of the Notification.
	Id *string `json:"id,omitempty"`
	Locale *LocaleCode `json:"locale,omitempty"`
	// The ID of recipient.
	RecipientId *string `json:"recipient_id,omitempty"`
	// The name of the recipient.
	ToName *string `json:"to_name,omitempty"`
	// The email address of the recipient.
	ToEmailAddress *string `json:"to_email_address,omitempty"`
	// The name of the sender.
	FromName *string `json:"from_name,omitempty"`
	// The email address of the sender.
	FromEmailAddress *string `json:"from_email_address,omitempty"`
	// The state of the Notification status.  - 1: Notification Accepted  - 2: Notification Blocked  - 3: Notification Sent  - 4: Notification Not Sent  - 5: Notification Delivered  - 6: Notification Not Delivered
	Status *int32 `json:"status,omitempty"`
	// The custom parameters of the notification.
	CustomParams map[string]interface{} `json:"custom_params,omitempty"`
	// The datetime when the Notification was created.
	CreatedAt *time.Time `json:"created_at,omitempty"`
}

// NewEmailNotification instantiates a new EmailNotification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailNotification() *EmailNotification {
	this := EmailNotification{}
	return &this
}

// NewEmailNotificationWithDefaults instantiates a new EmailNotification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailNotificationWithDefaults() *EmailNotification {
	this := EmailNotification{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *EmailNotification) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailNotification) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *EmailNotification) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *EmailNotification) SetId(v string) {
	o.Id = &v
}

// GetLocale returns the Locale field value if set, zero value otherwise.
func (o *EmailNotification) GetLocale() LocaleCode {
	if o == nil || IsNil(o.Locale) {
		var ret LocaleCode
		return ret
	}
	return *o.Locale
}

// GetLocaleOk returns a tuple with the Locale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailNotification) GetLocaleOk() (*LocaleCode, bool) {
	if o == nil || IsNil(o.Locale) {
		return nil, false
	}
	return o.Locale, true
}

// HasLocale returns a boolean if a field has been set.
func (o *EmailNotification) HasLocale() bool {
	if o != nil && !IsNil(o.Locale) {
		return true
	}

	return false
}

// SetLocale gets a reference to the given LocaleCode and assigns it to the Locale field.
func (o *EmailNotification) SetLocale(v LocaleCode) {
	o.Locale = &v
}

// GetRecipientId returns the RecipientId field value if set, zero value otherwise.
func (o *EmailNotification) GetRecipientId() string {
	if o == nil || IsNil(o.RecipientId) {
		var ret string
		return ret
	}
	return *o.RecipientId
}

// GetRecipientIdOk returns a tuple with the RecipientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailNotification) GetRecipientIdOk() (*string, bool) {
	if o == nil || IsNil(o.RecipientId) {
		return nil, false
	}
	return o.RecipientId, true
}

// HasRecipientId returns a boolean if a field has been set.
func (o *EmailNotification) HasRecipientId() bool {
	if o != nil && !IsNil(o.RecipientId) {
		return true
	}

	return false
}

// SetRecipientId gets a reference to the given string and assigns it to the RecipientId field.
func (o *EmailNotification) SetRecipientId(v string) {
	o.RecipientId = &v
}

// GetToName returns the ToName field value if set, zero value otherwise.
func (o *EmailNotification) GetToName() string {
	if o == nil || IsNil(o.ToName) {
		var ret string
		return ret
	}
	return *o.ToName
}

// GetToNameOk returns a tuple with the ToName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailNotification) GetToNameOk() (*string, bool) {
	if o == nil || IsNil(o.ToName) {
		return nil, false
	}
	return o.ToName, true
}

// HasToName returns a boolean if a field has been set.
func (o *EmailNotification) HasToName() bool {
	if o != nil && !IsNil(o.ToName) {
		return true
	}

	return false
}

// SetToName gets a reference to the given string and assigns it to the ToName field.
func (o *EmailNotification) SetToName(v string) {
	o.ToName = &v
}

// GetToEmailAddress returns the ToEmailAddress field value if set, zero value otherwise.
func (o *EmailNotification) GetToEmailAddress() string {
	if o == nil || IsNil(o.ToEmailAddress) {
		var ret string
		return ret
	}
	return *o.ToEmailAddress
}

// GetToEmailAddressOk returns a tuple with the ToEmailAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailNotification) GetToEmailAddressOk() (*string, bool) {
	if o == nil || IsNil(o.ToEmailAddress) {
		return nil, false
	}
	return o.ToEmailAddress, true
}

// HasToEmailAddress returns a boolean if a field has been set.
func (o *EmailNotification) HasToEmailAddress() bool {
	if o != nil && !IsNil(o.ToEmailAddress) {
		return true
	}

	return false
}

// SetToEmailAddress gets a reference to the given string and assigns it to the ToEmailAddress field.
func (o *EmailNotification) SetToEmailAddress(v string) {
	o.ToEmailAddress = &v
}

// GetFromName returns the FromName field value if set, zero value otherwise.
func (o *EmailNotification) GetFromName() string {
	if o == nil || IsNil(o.FromName) {
		var ret string
		return ret
	}
	return *o.FromName
}

// GetFromNameOk returns a tuple with the FromName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailNotification) GetFromNameOk() (*string, bool) {
	if o == nil || IsNil(o.FromName) {
		return nil, false
	}
	return o.FromName, true
}

// HasFromName returns a boolean if a field has been set.
func (o *EmailNotification) HasFromName() bool {
	if o != nil && !IsNil(o.FromName) {
		return true
	}

	return false
}

// SetFromName gets a reference to the given string and assigns it to the FromName field.
func (o *EmailNotification) SetFromName(v string) {
	o.FromName = &v
}

// GetFromEmailAddress returns the FromEmailAddress field value if set, zero value otherwise.
func (o *EmailNotification) GetFromEmailAddress() string {
	if o == nil || IsNil(o.FromEmailAddress) {
		var ret string
		return ret
	}
	return *o.FromEmailAddress
}

// GetFromEmailAddressOk returns a tuple with the FromEmailAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailNotification) GetFromEmailAddressOk() (*string, bool) {
	if o == nil || IsNil(o.FromEmailAddress) {
		return nil, false
	}
	return o.FromEmailAddress, true
}

// HasFromEmailAddress returns a boolean if a field has been set.
func (o *EmailNotification) HasFromEmailAddress() bool {
	if o != nil && !IsNil(o.FromEmailAddress) {
		return true
	}

	return false
}

// SetFromEmailAddress gets a reference to the given string and assigns it to the FromEmailAddress field.
func (o *EmailNotification) SetFromEmailAddress(v string) {
	o.FromEmailAddress = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *EmailNotification) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailNotification) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *EmailNotification) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *EmailNotification) SetStatus(v int32) {
	o.Status = &v
}

// GetCustomParams returns the CustomParams field value if set, zero value otherwise.
func (o *EmailNotification) GetCustomParams() map[string]interface{} {
	if o == nil || IsNil(o.CustomParams) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomParams
}

// GetCustomParamsOk returns a tuple with the CustomParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailNotification) GetCustomParamsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomParams) {
		return map[string]interface{}{}, false
	}
	return o.CustomParams, true
}

// HasCustomParams returns a boolean if a field has been set.
func (o *EmailNotification) HasCustomParams() bool {
	if o != nil && !IsNil(o.CustomParams) {
		return true
	}

	return false
}

// SetCustomParams gets a reference to the given map[string]interface{} and assigns it to the CustomParams field.
func (o *EmailNotification) SetCustomParams(v map[string]interface{}) {
	o.CustomParams = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *EmailNotification) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailNotification) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *EmailNotification) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *EmailNotification) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

func (o EmailNotification) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailNotification) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Locale) {
		toSerialize["locale"] = o.Locale
	}
	if !IsNil(o.RecipientId) {
		toSerialize["recipient_id"] = o.RecipientId
	}
	if !IsNil(o.ToName) {
		toSerialize["to_name"] = o.ToName
	}
	if !IsNil(o.ToEmailAddress) {
		toSerialize["to_email_address"] = o.ToEmailAddress
	}
	if !IsNil(o.FromName) {
		toSerialize["from_name"] = o.FromName
	}
	if !IsNil(o.FromEmailAddress) {
		toSerialize["from_email_address"] = o.FromEmailAddress
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.CustomParams) {
		toSerialize["custom_params"] = o.CustomParams
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableEmailNotification struct {
	value *EmailNotification
	isSet bool
}

func (v NullableEmailNotification) Get() *EmailNotification {
	return v.value
}

func (v *NullableEmailNotification) Set(val *EmailNotification) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailNotification) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailNotification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailNotification(val *EmailNotification) *NullableEmailNotification {
	return &NullableEmailNotification{value: val, isSet: true}
}

func (v NullableEmailNotification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailNotification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


