/*
airEml - API

airEml - API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package AirEml

import (
	"encoding/json"
)

// checks if the SmsMultipleNotificationSentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SmsMultipleNotificationSentResponse{}

// SmsMultipleNotificationSentResponse struct for SmsMultipleNotificationSentResponse
type SmsMultipleNotificationSentResponse struct {
	Data []EmailSendResponseData `json:"data,omitempty"`
}

// NewSmsMultipleNotificationSentResponse instantiates a new SmsMultipleNotificationSentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSmsMultipleNotificationSentResponse() *SmsMultipleNotificationSentResponse {
	this := SmsMultipleNotificationSentResponse{}
	return &this
}

// NewSmsMultipleNotificationSentResponseWithDefaults instantiates a new SmsMultipleNotificationSentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSmsMultipleNotificationSentResponseWithDefaults() *SmsMultipleNotificationSentResponse {
	this := SmsMultipleNotificationSentResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *SmsMultipleNotificationSentResponse) GetData() []EmailSendResponseData {
	if o == nil || IsNil(o.Data) {
		var ret []EmailSendResponseData
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmsMultipleNotificationSentResponse) GetDataOk() ([]EmailSendResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *SmsMultipleNotificationSentResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []EmailSendResponseData and assigns it to the Data field.
func (o *SmsMultipleNotificationSentResponse) SetData(v []EmailSendResponseData) {
	o.Data = v
}

func (o SmsMultipleNotificationSentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SmsMultipleNotificationSentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableSmsMultipleNotificationSentResponse struct {
	value *SmsMultipleNotificationSentResponse
	isSet bool
}

func (v NullableSmsMultipleNotificationSentResponse) Get() *SmsMultipleNotificationSentResponse {
	return v.value
}

func (v *NullableSmsMultipleNotificationSentResponse) Set(val *SmsMultipleNotificationSentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSmsMultipleNotificationSentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSmsMultipleNotificationSentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSmsMultipleNotificationSentResponse(val *SmsMultipleNotificationSentResponse) *NullableSmsMultipleNotificationSentResponse {
	return &NullableSmsMultipleNotificationSentResponse{value: val, isSet: true}
}

func (v NullableSmsMultipleNotificationSentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSmsMultipleNotificationSentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


