/*
airEml - API

airEml - API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package AirEml

import (
	"encoding/json"
)

// checks if the EmailSenderResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailSenderResponse{}

// EmailSenderResponse struct for EmailSenderResponse
type EmailSenderResponse struct {
	Data *EmailSender `json:"data,omitempty"`
}

// NewEmailSenderResponse instantiates a new EmailSenderResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailSenderResponse() *EmailSenderResponse {
	this := EmailSenderResponse{}
	return &this
}

// NewEmailSenderResponseWithDefaults instantiates a new EmailSenderResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailSenderResponseWithDefaults() *EmailSenderResponse {
	this := EmailSenderResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *EmailSenderResponse) GetData() EmailSender {
	if o == nil || IsNil(o.Data) {
		var ret EmailSender
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailSenderResponse) GetDataOk() (*EmailSender, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *EmailSenderResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given EmailSender and assigns it to the Data field.
func (o *EmailSenderResponse) SetData(v EmailSender) {
	o.Data = &v
}

func (o EmailSenderResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailSenderResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableEmailSenderResponse struct {
	value *EmailSenderResponse
	isSet bool
}

func (v NullableEmailSenderResponse) Get() *EmailSenderResponse {
	return v.value
}

func (v *NullableEmailSenderResponse) Set(val *EmailSenderResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailSenderResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailSenderResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailSenderResponse(val *EmailSenderResponse) *NullableEmailSenderResponse {
	return &NullableEmailSenderResponse{value: val, isSet: true}
}

func (v NullableEmailSenderResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailSenderResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


