/*
airEml - API

airEml - API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package AirEml

import (
	"encoding/json"
)

// checks if the PushPlatformResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PushPlatformResponse{}

// PushPlatformResponse struct for PushPlatformResponse
type PushPlatformResponse struct {
	Data *PushPlatform `json:"data,omitempty"`
}

// NewPushPlatformResponse instantiates a new PushPlatformResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPushPlatformResponse() *PushPlatformResponse {
	this := PushPlatformResponse{}
	return &this
}

// NewPushPlatformResponseWithDefaults instantiates a new PushPlatformResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPushPlatformResponseWithDefaults() *PushPlatformResponse {
	this := PushPlatformResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *PushPlatformResponse) GetData() PushPlatform {
	if o == nil || IsNil(o.Data) {
		var ret PushPlatform
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PushPlatformResponse) GetDataOk() (*PushPlatform, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *PushPlatformResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given PushPlatform and assigns it to the Data field.
func (o *PushPlatformResponse) SetData(v PushPlatform) {
	o.Data = &v
}

func (o PushPlatformResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PushPlatformResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullablePushPlatformResponse struct {
	value *PushPlatformResponse
	isSet bool
}

func (v NullablePushPlatformResponse) Get() *PushPlatformResponse {
	return v.value
}

func (v *NullablePushPlatformResponse) Set(val *PushPlatformResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePushPlatformResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePushPlatformResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePushPlatformResponse(val *PushPlatformResponse) *NullablePushPlatformResponse {
	return &NullablePushPlatformResponse{value: val, isSet: true}
}

func (v NullablePushPlatformResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePushPlatformResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


