openapi: 3.0.3
info:
  contact:
    name: airEml
  description: airEml - API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.txt
  title: airEml - API
  version: 1.0.0
servers:
- description: PROD server
  url: https://aireml.com
- description: Dev server
  url: https://deveml.com
- description: RC server
  url: https://rceml.com
tags:
- description: Authorization group
  name: Authorization
- description: The audience resources
  name: Audience
- description: The sending of Notifications
  name: Sending
- description: The Notifications resources
  name: Notifications
- description: The email templates resources
  name: Email Templates
- description: The email transport settings
  name: Email Settings
- description: The push templates resources
  name: Push Templates
- description: The push transport settings
  name: Push Settings
- description: The SMS templates resources
  name: SMS Templates
- description: The SMS transport settings
  name: SMS Settings
- description: The Webhook resources
  name: Webhooks
paths:
  /api/v1/audience/segments:
    get:
      description: To retrieve a list of all segments from your audience.
      operationId: list_audience_segments
      security:
      - bearerAuth:
        - audience.segments:read
        - audience.segments:read_write
      summary: List All Segments
      tags:
      - Audience
    post:
      description: To create a new segment in your audience.
      operationId: create_audience_segment
      security:
      - bearerAuth:
        - audience.segments:read_write
      summary: Create a New Segment
      tags:
      - Audience
  /api/v1/audience/segments/{audience_segment_id}:
    delete:
      description: To delete a segment from your audience.
      operationId: delete_audience_segment
      security:
      - bearerAuth:
        - audience.segments:read_write
      summary: Delete a Segment
      tags:
      - Audience
    get:
      description: To get details about a specific segment in your audience.
      operationId: get_audience_segment
      security:
      - bearerAuth:
        - audience.segments:read
        - audience.segments:read_write
      summary: Retrieve an Existing Segment
      tags:
      - Audience
    put:
      description: To update details about a specific segment in your audience.
      operationId: update_audience_segment
      security:
      - bearerAuth:
        - audience.segments:read_write
      summary: Update a Segment
      tags:
      - Audience
  /api/v1/audience/segments/{audience_segment_id}/activate:
    put:
      description: To activate a segment.
      operationId: update_assign_active_status_to_audience_segment
      security:
      - bearerAuth:
        - audience.segments:read_write
      summary: Activate a Segment
      tags:
      - Audience
  /api/v1/audience/segments/{audience_segment_id}/deactivate:
    put:
      description: To deactivate a segment.
      operationId: update_assign_inactive_status_to_audience_segment
      security:
      - bearerAuth:
        - audience.segments:read_write
      summary: Deactivate a Segment
      tags:
      - Audience
  /api/v1/audience/segments/{audience_segment_id}/filters:
    get:
      description: To retrieve a list of all filters from the specific audience segment
        in your workspace.
      operationId: list_audience_segment_filters
      security:
      - bearerAuth:
        - audience.segments:read
        - audience.segments:read_write
      summary: List All Filters from the Segment
      tags:
      - Audience
    post:
      description: To create a new filter for the audience segment in your workspace.
      operationId: create_audience_segment_filter
      security:
      - bearerAuth:
        - audience.segments:read_write
      summary: Create a New Segment Filter
      tags:
      - Audience
  /api/v1/audience/segments/{audience_segment_id}/filters/{audience_filter_id}:
    delete:
      description: To delete a filter from the specific audience segment in your workspace.
      operationId: delete_audience_segment_filter
      security:
      - bearerAuth:
        - audience.segments:read_write
      summary: Delete a Filter from the Audience Segment
      tags:
      - Audience
    get:
      description: To get details about the specific filter of the audience segment
        in your workspace.
      operationId: get_audience_segment_filter
      security:
      - bearerAuth:
        - audience.segments:read
        - audience.segments:read_write
      summary: Retrieve an Existing Filter from the Audience Segment
      tags:
      - Audience
    put:
      description: To update details about specific filter in the audience segment
        in your workspace.
      operationId: update_audience_segment_filter
      security:
      - bearerAuth:
        - audience.segments:read_write
      summary: Update a Filter in the Audience Segment
      tags:
      - Audience
  /api/v1/audience/tags:
    get:
      description: To retrieve a list of all tags from your audience.
      operationId: list_audience_tags
      security:
      - bearerAuth:
        - audience.recipients:read
        - audience.recipients:read_write
      summary: List All Tags
      tags:
      - Audience
    post:
      description: To create a new tag in your audience.
      operationId: create_audience_tag
      security:
      - bearerAuth:
        - audience.recipients:read_write
      summary: Create a New Tag
      tags:
      - Audience
  /api/v1/audience/tags/{audience_tag_id}:
    delete:
      description: To delete a tag from your audience.
      operationId: delete_audience_tag
      security:
      - bearerAuth:
        - audience.recipients:read_write
      summary: Delete a Tag
      tags:
      - Audience
    get:
      description: To get details about a specific tag in your audience.
      operationId: get_audience_tag
      security:
      - bearerAuth:
        - audience.recipients:read
        - audience.recipients:read_write
      summary: Retrieve an Existing Tag
      tags:
      - Audience
    put:
      description: To update details about a specific tag in your audience.
      operationId: update_audience_tag
      security:
      - bearerAuth:
        - audience.recipients:read_write
      summary: Update a Tag
      tags:
      - Audience
  /api/v1/audience/recipients:
    get:
      description: To retrieve a list of all recipients from your audience.
      operationId: list_audience_recipients
      security:
      - bearerAuth:
        - audience.recipients:read
        - audience.recipients:read_write
      summary: List All Recipients
      tags:
      - Audience
    post:
      description: To create a new recipient in your audience.
      operationId: create_audience_recipient
      security:
      - bearerAuth:
        - audience.recipients:read_write
      summary: Create a New Recipient
      tags:
      - Audience
  /api/v1/audience/recipients/{audience_recipient_id}:
    delete:
      description: To delete a recipient from your audience.
      operationId: delete_audience_recipient
      security:
      - bearerAuth:
        - audience.recipients:read_write
      summary: Delete a Recipient
      tags:
      - Audience
    get:
      description: To get details about a specific recipient in your audience.
      operationId: get_audience_recipient
      security:
      - bearerAuth:
        - audience.recipients:read
        - audience.recipients:read_write
      summary: Retrieve an Existing Recipient
      tags:
      - Audience
    put:
      description: To update details about a specific recipient in your audience.
      operationId: update_audience_recipient
      security:
      - bearerAuth:
        - audience.recipients:read_write
      summary: Update a Recipient
      tags:
      - Audience
  /api/v1/audience/recipients/{audience_recipient_id}/contacts/{audience_contact_type}:
    delete:
      description: To delete a contact from the specific audience recipient in your
        workspace.
      operationId: delete_audience_recipient_contact
      security:
      - bearerAuth:
        - audience.recipients:read_write
      summary: Delete a Contact from the Audience Recipient
      tags:
      - Audience
    post:
      description: To attach a contact to the audience recipient in your workspace.
      operationId: attach_audience_recipient_contact
      security:
      - bearerAuth:
        - audience.recipients:read_write
      summary: Attach a Contact to the Audience Recipient
      tags:
      - Audience
  /api/v1/audience/recipients/{audience_recipient_id}/segments:
    get:
      description: To retrieve a list of all segments from the specific audience recipient
        in your workspace.
      operationId: list_audience_recipient_segments
      security:
      - bearerAuth:
        - audience.recipients:read
        - audience.recipients:read_write
        - audience.segments:read
        - audience.segments:read_write
      summary: List All Segments from the Recipient
      tags:
      - Audience
  /api/v1/audience/recipients/{audience_recipient_id}/tags/{audience_tag_name}:
    delete:
      description: To delete a tag from the specific audience recipient in your workspace.
      operationId: delete_audience_recipient_tag
      security:
      - bearerAuth:
        - audience.recipients:read_write
      summary: Delete a Tag from the Audience Recipient
      tags:
      - Audience
    post:
      description: To attach a tag to the audience recipient in your workspace.
      operationId: attach_audience_recipient_tag
      security:
      - bearerAuth:
        - audience.recipients:read_write
      summary: Attach a Tag to the Audience Recipient
      tags:
      - Audience
  /api/v1/auth/tokens/service-account:
    post:
      description: To create an access token for the service account by client id
        and client secret (machine-to-machine authentication).
      operationId: create_auth_token_for_service_account
      security: []
      summary: Create Access Token for Service Account
      tags:
      - Authorization
  /api/v1/email/transports:
    get:
      description: To retrieve a list of all email notification transports in your
        workspace.
      operationId: list_email_transports
      security:
      - bearerAuth:
        - email.transports:read
        - email.transports:read_write
      summary: List All Email Notification Transports
      tags:
      - Email Settings
    post:
      description: To create a new email notification transport in your workspace.
      operationId: create_email_transport
      security:
      - bearerAuth:
        - email.transports:read_write
      summary: Create a New Email Notification Transport
      tags:
      - Email Settings
  /api/v1/email/transports/{transport_id}:
    delete:
      description: To delete a email notification transport in your workspace.
      operationId: delete_email_transport
      security:
      - bearerAuth:
        - email.transports:read_write
      summary: Delete a Email Notification Transport
      tags:
      - Email Settings
    get:
      description: To get details about a specific email notification transport in
        your workspace.
      operationId: get_email_transport
      security:
      - bearerAuth:
        - email.transports:read
        - email.transports:read_write
      summary: Retrieve an Existing Email Notification Transport
      tags:
      - Email Settings
    put:
      description: To update details about a specific email notification transport
        in your workspace.
      operationId: update_email_transport
      security:
      - bearerAuth:
        - email.transports:read_write
      summary: Update a Email Notification Transport
      tags:
      - Email Settings
  /api/v1/email/channels:
    get:
      description: To retrieve a list of all email notification channels in your workspace.
      operationId: list_email_channels
      security:
      - bearerAuth:
        - email.channels:read
        - email.channels:read_write
      summary: List All Email Notification Channels
      tags:
      - Email Settings
    post:
      description: To create a new email notification channel in your workspace.
      operationId: create_email_channel
      security:
      - bearerAuth:
        - email.channels:read_write
      summary: Create a New Email Notification Channel
      tags:
      - Email Settings
  /api/v1/email/channels/{channel_id}:
    delete:
      description: To delete a email notification channel in your workspace.
      operationId: delete_email_channel
      security:
      - bearerAuth:
        - email.channels:read_write
      summary: Delete a Email Notification Channel
      tags:
      - Email Settings
    get:
      description: To get details about a specific email notification channel in your
        workspace.
      operationId: get_email_channel
      security:
      - bearerAuth:
        - email.channels:read
        - email.channels:read_write
      summary: Retrieve an Existing Email Notification Channel
      tags:
      - Email Settings
    put:
      description: To update details about a specific email notification channel in
        your workspace.
      operationId: update_email_channel
      security:
      - bearerAuth:
        - email.channels:read_write
      summary: Update a Email Notification Channel
      tags:
      - Email Settings
  /api/v1/email/channels/{channel_id}/routing-rules:
    get:
      description: To retrieve a list of all routing-rules from the specific email
        notification channel in your workspace.
      operationId: list_email_channel_routing-rules
      security:
      - bearerAuth:
        - email.channels:read
        - email.channels:read_write
      summary: List All Routing-rules from the Email Notification Channel
      tags:
      - Email Settings
    post:
      description: Create to a routing-rule in the email notification channel in your
        workspace.
      operationId: create_email_channel_routing-rule
      security:
      - bearerAuth:
        - email.channels:read_write
      summary: Create a Routing-rule in the Email Notification Channel
      tags:
      - Email Settings
  /api/v1/email/channels/{channel_id}/routing-rules/{routing_rule_id}:
    delete:
      description: To delete a routing-rule from the specific email notification channel
        in your workspace.
      operationId: delete_email_channel_routing_rule
      security:
      - bearerAuth:
        - email.channels:read_write
      summary: Delete a Routing-rule from the Email Notification Channel
      tags:
      - Email Settings
    get:
      description: To get details about the specific routing-rule of the email notification
        channel in your workspace.
      operationId: get_email_channel_routing_rule
      security:
      - bearerAuth:
        - email.channels:read
        - email.channels:read_write
      summary: Retrieve an Existing Routing-rule from the Email Notification Channel
      tags:
      - Email Settings
    put:
      description: Update to a routing-rule in the email notification channel in your
        workspace.
      operationId: update_email_channel_routing_rule
      security:
      - bearerAuth:
        - email.channels:read_write
      summary: Update a Routing-rule in the Email Notification Channel
      tags:
      - Email Settings
  /api/v1/email/send:
    post:
      description: To send an email notification using your workspace resources.
      operationId: send_email
      security:
      - bearerAuth:
        - email.notifications:send
      summary: Send Email
      tags:
      - Sending
  /api/v1/email/send/batch:
    post:
      description: To send batch of email notifications using your workspace resources.
      operationId: send_email_batch
      security:
      - bearerAuth:
        - email.notifications:send
      summary: Send Email Batch
      tags:
      - Sending
  /api/v1/email/senders:
    get:
      description: To retrieve a list of all email notification senders in your workspace.
      operationId: list_email_senders
      security:
      - bearerAuth:
        - email.senders:read
        - email.senders:read_write
      summary: List All Email Notification Senders
      tags:
      - Email Settings
    post:
      description: To create a new email notification sender in your workspace.
      operationId: create_email_sender
      security:
      - bearerAuth:
        - email.senders:read_write
      summary: Create a New Email Notification Sender
      tags:
      - Email Settings
  /api/v1/email/senders/{sender_id}:
    delete:
      description: To delete a email notification sender in your workspace.
      operationId: delete_email_sender
      security:
      - bearerAuth:
        - email.senders:read_write
      summary: Delete a Email Notification Sender
      tags:
      - Email Settings
    get:
      description: To get details about a specific email notification sender in your
        workspace.
      operationId: get_email_sender
      security:
      - bearerAuth:
        - email.senders:read
        - email.senders:read_write
      summary: Retrieve an Existing Email Notification Sender
      tags:
      - Email Settings
    put:
      description: To update details about a specific email notification sender in
        your workspace.
      operationId: update_email_sender
      security:
      - bearerAuth:
        - email.senders:read_write
      summary: Update a Email Notification Sender
      tags:
      - Email Settings
  /api/v1/email/templates:
    get:
      description: To retrieve a list of all email notification templates in your
        workspace.
      operationId: list_email_templates
      security:
      - bearerAuth:
        - email.templates:read
        - email.templates:read_write
      summary: List All Email Notification Templates
      tags:
      - Email Templates
    post:
      description: To create a new email notification template in your workspace.
      operationId: create_email_template
      security:
      - bearerAuth:
        - email.templates:read_write
      summary: Create a New Email Notification Template
      tags:
      - Email Templates
  /api/v1/email/templates/{template_id}:
    delete:
      description: To delete a email notification template in your workspace.
      operationId: delete_email_template
      security:
      - bearerAuth:
        - email.templates:read_write
      summary: Delete a Email Notification Template
      tags:
      - Email Templates
    get:
      description: To get details about a specific email notification template in
        your workspace.
      operationId: get_email_template
      security:
      - bearerAuth:
        - email.templates:read
        - email.templates:read_write
      summary: Retrieve an Existing Email Notification Template
      tags:
      - Email Templates
    put:
      description: To update details about a specific email notification template
        in your workspace.
      operationId: update_email_template
      security:
      - bearerAuth:
        - email.templates:read_write
      summary: Update a Email Notification Template
      tags:
      - Email Templates
  /api/v1/email/templates/{template_id}/contents:
    get:
      description: To retrieve a list of all contents from the specific email notification
        template in your workspace.
      operationId: list_email_template_contents
      security:
      - bearerAuth:
        - email.templates:read
        - email.templates:read_write
      summary: List All Contents from the Email Notification Template
      tags:
      - Email Templates
  /api/v1/email/templates/{template_id}/contents/{template_content_locale}:
    delete:
      description: To delete a content from the specific email notification template
        in your workspace.
      operationId: delete_email_template_content
      security:
      - bearerAuth:
        - email.templates:read_write
      summary: Delete a Content from the Email Notification Template
      tags:
      - Email Templates
    get:
      description: To get details about the specific content of the email notification
        template in your workspace.
      operationId: get_email_template_content
      security:
      - bearerAuth:
        - email.templates:read
        - email.templates:read_write
      summary: Retrieve an Existing Content from the Email Notification Template
      tags:
      - Email Templates
    post:
      description: Create to a content in the email notification template in your
        workspace.
      operationId: create_email_template_content
      security:
      - bearerAuth:
        - email.templates:read_write
      summary: Create a Content in the Email Notification Template
      tags:
      - Email Templates
    put:
      description: Update to a content in the email notification template in your
        workspace.
      operationId: update_email_template_content
      security:
      - bearerAuth:
        - email.templates:read_write
      summary: Update a Content in the Email Notification Template
      tags:
      - Email Templates
  /api/v1/email/notifications:
    get:
      description: To retrieve a list of all email notifications in your workspace.
      operationId: list_email_notifications
      security:
      - bearerAuth:
        - email.notifications:read
      summary: List All Email Notifications
      tags:
      - Notifications
  /api/v1/email/notifications/{notification_id}:
    get:
      description: To get details about a specific email notification in your workspace.
      operationId: get_email_notification
      security:
      - bearerAuth:
        - email.notifications:read
      summary: Retrieve an Existing Email Notification
      tags:
      - Notifications
  /api/v1/email/notifications/{notification_id}/states:
    get:
      description: To get details about a specific email notification status states
        in your workspace.
      operationId: get_email_notification_states
      security:
      - bearerAuth:
        - email.notification.states:read
      summary: Retrieve an Existing Email Notification States
      tags:
      - Notifications
  /api/v1/push/platforms:
    get:
      description: To retrieve a list of all push notification platforms in your workspace.
      operationId: list_push_platforms
      security:
      - bearerAuth:
        - push.platforms:read
        - push.platforms:read_write
      summary: List All Push Notification Platforms
      tags:
      - Push Settings
    post:
      description: To create a new push notification platform in your workspace.
      operationId: create_push_platform
      security:
      - bearerAuth:
        - push.platforms:read_write
      summary: Create a New Push Notification Platform
      tags:
      - Push Settings
  /api/v1/push/platforms/{platform_id}:
    delete:
      description: To delete a push notification platform in your workspace.
      operationId: delete_push_platforms
      security:
      - bearerAuth:
        - push.platforms:read_write
      summary: Delete a Push Notification Platform
      tags:
      - Push Settings
    get:
      description: To get details about a specific push notification platform in your
        workspace.
      operationId: get_push_platform
      security:
      - bearerAuth:
        - push.platforms:read
        - push.platforms:read_write
      summary: Retrieve an Existing Push Notification Platform
      tags:
      - Push Settings
    put:
      description: To update details about a specific push notification platform in
        your workspace.
      operationId: update_push_platform
      security:
      - bearerAuth:
        - push.platforms:read_write
      summary: Update a Push Notification Platform
      tags:
      - Push Settings
  /api/v1/push/templates:
    get:
      description: To retrieve a list of all push notification templates in your workspace.
      operationId: list_push_templates
      security:
      - bearerAuth:
        - push.templates:read
        - push.templates:read_write
      summary: List All Push Notification Templates
      tags:
      - Push Templates
    post:
      description: To create a new push notification template in your workspace.
      operationId: create_push_template
      security:
      - bearerAuth:
        - push.templates:read_write
      summary: Create a New Push Notification Template
      tags:
      - Push Templates
  /api/v1/push/templates/{template_id}:
    delete:
      description: To delete a push notification template in your workspace.
      operationId: delete_push_template
      security:
      - bearerAuth:
        - push.templates:read_write
      summary: Delete a Push Notification Template
      tags:
      - Push Templates
    get:
      description: To get details about a specific push notification template in your
        workspace.
      operationId: get_push_template
      security:
      - bearerAuth:
        - push.templates:read
        - push.templates:read_write
      summary: Retrieve an Existing Push Notification Template
      tags:
      - Push Templates
    put:
      description: To update details about a specific push notification template in
        your workspace.
      operationId: update_push_template
      security:
      - bearerAuth:
        - push.templates:read_write
      summary: Update a Push Notification Template
      tags:
      - Push Templates
  /api/v1/push/templates/{template_id}/contents:
    get:
      description: To retrieve a list of all contents from the specific push notification
        template in your workspace.
      operationId: list_push_template_contents
      security:
      - bearerAuth:
        - push.templates:read
        - push.templates:read_write
      summary: List All Contents from the Push Notification Template
      tags:
      - Push Templates
  /api/v1/push/templates/{template_id}/contents/{template_content_locale}:
    delete:
      description: To delete a content from the specific push notification template
        in your workspace.
      operationId: delete_push_template_content
      security:
      - bearerAuth:
        - push.templates:read_write
      summary: Delete a Content from the Push Notification Template
      tags:
      - Push Templates
    get:
      description: To get details about the specific content of the push notification
        template in your workspace.
      operationId: get_push_template_content
      security:
      - bearerAuth:
        - push.templates:read
        - push.templates:read_write
      summary: Retrieve an Existing Content from the Push Notification Template
      tags:
      - Push Templates
    post:
      description: To create a content in the push notification template in your workspace.
      operationId: create_push_template_content
      security:
      - bearerAuth:
        - push.templates:read_write
      summary: Create a Content in the Push Notification Template
      tags:
      - Push Templates
    put:
      description: Update to a content in the push notification template in your workspace.
      operationId: update_push_template_content
      security:
      - bearerAuth:
        - push.templates:read_write
      summary: Update a Content in the Push Notification Template
      tags:
      - Push Templates
  /api/v1/push/notifications:
    get:
      description: To retrieve a list of all push notifications in your workspace.
      operationId: list_push_notifications
      security:
      - bearerAuth:
        - push.notifications:read
      summary: List All Push Notifications
      tags:
      - Notifications
  /api/v1/push/notifications/{notification_id}:
    get:
      description: To get details about a specific push notification in your workspace.
      operationId: get_push_notification
      security:
      - bearerAuth:
        - push.notifications:read
      summary: Retrieve an Existing Push Notification
      tags:
      - Notifications
  /api/v1/push/notifications/{notification_id}/states:
    get:
      description: To get details about a specific push notification status states
        in your workspace.
      operationId: get_push_notification_states
      security:
      - bearerAuth:
        - push.notification.states:read
      summary: Retrieve an Existing Push Notification States
      tags:
      - Notifications
  /api/v1/push/send:
    post:
      description: To send a new push notification using your workspace resources.
      operationId: send_push
      security:
      - bearerAuth:
        - push.notifications:send
      summary: Send Push Notification
      tags:
      - Sending
  /api/v1/sms/transports:
    get:
      description: To retrieve a list of all sms transports in your workspace.
      operationId: list_sms_transports
      security:
      - bearerAuth:
        - sms.transports:read
        - sms.transports:read_write
      summary: List All SMS Transports
      tags:
      - SMS Settings
    post:
      description: To create a new sms transport in your workspace.
      operationId: create_sms_transport
      security:
      - bearerAuth:
        - sms.transports:read_write
      summary: Create a New SMS Transport
      tags:
      - SMS Settings
  /api/v1/sms/transports/{transport_id}:
    delete:
      description: To delete a sms transport in your workspace.
      operationId: delete_sms_transport
      security:
      - bearerAuth:
        - sms.transports:read_write
      summary: Delete a SMS Transport
      tags:
      - SMS Settings
    get:
      description: To get details about a specific sms transport in your workspace.
      operationId: get_sms_transport
      security:
      - bearerAuth:
        - sms.transports:read
        - sms.transports:read_write
      summary: Retrieve an Existing SMS Transport
      tags:
      - SMS Settings
    put:
      description: To update details about a specific sms transport in your workspace.
      operationId: update_sms_transport
      security:
      - bearerAuth:
        - sms.transports:read_write
      summary: Update a SMS Transport
      tags:
      - SMS Settings
  /api/v1/sms/transports/{transport_id}/generate-webhook:
    get:
      description: You can generate webhook to set it manually into transport provider
        like amazon.
      operationId: get_webhook_by_transport
      security:
      - bearerAuth:
        - sms.transports:read
        - sms.transports:read_write
      summary: Webhook url generated by transport
      tags:
      - SMS Settings
  /api/v1/sms/transports/all/senders:
    get:
      description: To retrieve a list of all sms transport senders in your workspace.
      operationId: list_all_sms_senders
      security:
      - bearerAuth:
        - sms.transports:read
        - sms.transports:read_write
      summary: List All SMS Transport Numbers
      tags:
      - SMS Settings
  /api/v1/sms/transports/{transport_id}/senders:
    get:
      description: To retrieve a list of all senders from the specific SMS transport
        in your workspace.
      operationId: list_sms_senders
      security:
      - bearerAuth:
        - sms.transports:read
        - sms.transports:read_write
      summary: List All Numbers from the SMS Transport
      tags:
      - SMS Settings
  /api/v1/sms/transports/{transport_id}/senders/{sender_id}:
    get:
      description: To get details about the specific number of the SMS transport in
        your workspace.
      operationId: get_sms_sender
      security:
      - bearerAuth:
        - sms.transports:read
        - sms.transports:read_write
      summary: Retrieve an Existing Number from the SMS Transport
      tags:
      - SMS Settings
  /api/v1/sms/channels:
    get:
      description: To retrieve a list of all sms channels in your workspace.
      operationId: list_sms_channels
      security:
      - bearerAuth:
        - sms.channels:read
        - sms.channels:read_write
      summary: List All SMS Channels
      tags:
      - SMS Settings
    post:
      description: To create a new sms channel in your workspace.
      operationId: create_sms_channel
      security:
      - bearerAuth:
        - sms.channels:read_write
      summary: Create a New SMS Channel
      tags:
      - SMS Settings
  /api/v1/sms/channels/{channel_id}:
    delete:
      description: To delete a sms channel in your workspace.
      operationId: delete_sms_channel
      security:
      - bearerAuth:
        - sms.channels:read_write
      summary: Delete a SMS Channel
      tags:
      - SMS Settings
    get:
      description: To get details about a specific sms channel in your workspace.
      operationId: get_sms_channel
      security:
      - bearerAuth:
        - sms.channels:read
        - sms.channels:read_write
      summary: Retrieve an Existing SMS Channel
      tags:
      - SMS Settings
    put:
      description: To update details about a specific sms channel in your workspace.
      operationId: update_sms_channel
      security:
      - bearerAuth:
        - sms.channels:read_write
      summary: Update a SMS Channel
      tags:
      - SMS Settings
  /api/v1/sms/channels/{channel_id}/rules:
    get:
      description: To retrieve a list of all contents from the specific sms channel
        in your workspace.
      operationId: list_sms_channels_rules
      security:
      - bearerAuth:
        - sms.channels:read
        - sms.channels:read_write
      summary: List of all Rules from the SMS Channel
      tags:
      - SMS Settings
    post:
      description: To save configured channel rule in your workspace.
      operationId: save_sms_routing_rule
      security:
      - bearerAuth:
        - sms.channels:read_write
      summary: Save a parameters SMS Channel Rule
      tags:
      - SMS Settings
  /api/v1/sms/channels/{channel_id}/rules/{routing_rule_id}:
    delete:
      description: To delete channel rule from your workspace.
      operationId: delete_sms_routing_rule
      security:
      - bearerAuth:
        - sms.channels:read_write
      summary: Delete a SMS Channel Rule
      tags:
      - SMS Settings
    get:
      description: To get details about the channel rule of your workspace.
      operationId: get_sms_routing_rule
      security:
      - bearerAuth:
        - sms.channels:read
        - sms.channels:read_write
      summary: Retrieve an Existing SMS Channel Rule
      tags:
      - SMS Settings
    put:
      description: To update details about a specific sms channel rule in your workspace.
      operationId: update_sms_routing_rule
      security:
      - bearerAuth:
        - sms.channels:read_write
      summary: Update a SMS Channel Rule
      tags:
      - SMS Settings
  /api/v1/sms/templates:
    get:
      description: To retrieve a list of all sms templates in your workspace.
      operationId: list_sms_templates
      security:
      - bearerAuth:
        - sms.templates:read
        - sms.templates:read_write
      summary: List All SMS Templates
      tags:
      - SMS Templates
    post:
      description: To create a new sms template in your workspace.
      operationId: create_sms_template
      security:
      - bearerAuth:
        - sms.templates:read_write
      summary: Create a New SMS Template
      tags:
      - SMS Templates
  /api/v1/sms/templates/{template_id}:
    delete:
      description: To delete a sms template in your workspace.
      operationId: delete_sms_template
      security:
      - bearerAuth:
        - sms.templates:read_write
      summary: Delete a SMS Template
      tags:
      - SMS Templates
    get:
      description: To get details about a specific sms template in your workspace.
      operationId: get_sms_template
      security:
      - bearerAuth:
        - sms.templates:read
        - sms.templates:read_write
      summary: Retrieve an Existing SMS Template
      tags:
      - SMS Templates
    put:
      description: To update details about a specific sms template in your workspace.
      operationId: update_sms_template
      security:
      - bearerAuth:
        - sms.templates:read_write
      summary: Update a SMS Template
      tags:
      - SMS Templates
  /api/v1/sms/templates/{template_id}/contents:
    get:
      description: To retrieve a list of all contents from the specific sms template
        in your workspace.
      operationId: list_sms_template_contents
      security:
      - bearerAuth:
        - sms.templates:read
        - sms.templates:read_write
      summary: List All Contents from the SMS Template
      tags:
      - SMS Templates
  /api/v1/sms/templates/{template_id}/contents/{template_content_locale}:
    delete:
      description: To delete a content from the specific sms template in your workspace.
      operationId: delete_sms_template_content
      security:
      - bearerAuth:
        - sms.templates:read_write
      summary: Delete a Content from the SMS Template
      tags:
      - SMS Templates
    get:
      description: To get details about the specific content of the sms template in
        your workspace.
      operationId: get_sms_template_content
      security:
      - bearerAuth:
        - sms.templates:read
        - sms.templates:read_write
      summary: Retrieve an Existing Content from the SMS Template
      tags:
      - SMS Templates
    post:
      description: To save content of the sms template in your workspace.
      operationId: save_sms_template_content
      security:
      - bearerAuth:
        - sms.templates:read_write
      summary: Save a Content in the SMS Template
      tags:
      - SMS Templates
    put:
      description: Update to a content in the SMS notification template in your workspace.
      operationId: update_sms_template_content
      security:
      - bearerAuth:
        - sms.templates:read_write
      summary: Update a Content in the SMS Notification Template
      tags:
      - SMS Templates
  /api/v1/sms/notifications:
    get:
      description: To retrieve a list of all sms notifications in your workspace.
      operationId: list_sms_notifications
      security:
      - bearerAuth:
        - sms.notifications:read
      summary: List All SMS Notifications
      tags:
      - Notifications
  /api/v1/sms/send:
    post:
      description: To send a new sms notification using your workspace resources.
      operationId: send_sms_notification
      security:
      - bearerAuth:
        - sms.notifications:send
      summary: Send SMS Notification
      tags:
      - Sending
  /api/v1/sms/send/batch:
    post:
      description: To send a new sms batch notification using your workspace resources.
      operationId: send_sms_batch_notification
      security:
      - bearerAuth:
        - sms.notifications:send
      summary: Send SMS Batch Notification
      tags:
      - Sending
  /api/v1/sms/notifications/{notification_id}:
    get:
      description: To get details about a specific sms notification in your workspace.
      operationId: get_sms_notification
      security:
      - bearerAuth:
        - sms.notifications:read
      summary: Retrieve an Existing SMS Notification
      tags:
      - Notifications
  /api/v1/sms/notifications/{notification_id}/states:
    get:
      description: To get details about a specific sms notification status states
        in your workspace.
      operationId: get_sms_notification_states
      security:
      - bearerAuth:
        - sms.notification.states:read
      summary: Retrieve an Existing Sms Notification States
      tags:
      - Notifications
  /api/v1/webhook/subscriptions:
    get:
      description: To retrieve a list of all webhook subscriptions in your workspace.
      operationId: list_webhook_subscriptions
      security:
      - bearerAuth: []
      summary: List All webhook Subscriptions
      tags:
      - Webhooks
    post:
      description: To create a new subscription in your workspace.
      operationId: create_webhook_subscription
      security:
      - bearerAuth: []
      summary: Create a New Subscription
      tags:
      - Webhooks
  /api/v1/webhook/subscriptions/{webhook_subscription_id}:
    delete:
      description: To delete a webhook subscription in your workspace.
      operationId: delete_webhook_subscription
      security:
      - bearerAuth: []
      summary: Delete a webhook subscription
      tags:
      - Webhooks
    get:
      description: To get details about a specific subscription in your workspace.
      operationId: get_webhook_subscription
      security:
      - bearerAuth: []
      summary: Retrieve an Existing webhook subscription
      tags:
      - Webhooks
    put:
      description: To update details about a specific webhook subscription in your
        workspace.
      operationId: update_webhook_subscription
      security:
      - bearerAuth: []
      summary: Update a webhook subscription
      tags:
      - Webhooks
  /api/v1/webhook/events:
    get:
      description: To retrieve a list of all webhook events.
      operationId: list_webhook_events
      security:
      - bearerAuth: []
      summary: List All Webhook events
      tags:
      - Webhooks
components:
  securitySchemes:
    oAuth2ClientCredentials:
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: https://aireml.com/api/v1/auth/tokens/service-account
      type: oauth2
